# -*- coding: utf-8 -*-
"""Lambdas.PY

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hw3SF_tFW5Pmutc4chHGTTXP6MOqhjGI
"""

soma = lambda lista:sum(lista)
numeros = [0,5,10,50]
total = soma(numeros)
print('A soma é igual a = {}'.format(total))

numeros = [80,75,25]
total = soma(numeros)
print('A soma é igual a = {}'.format(total))

lista = [1,2,3,4,5,6]
lista1 = list(map(lambda x:x**2,lista))

print("lista =",lista,"\n\nlista1 = ",lista1)

from functools import reduce

lista = [1,2,3,4,5,6]
produto = reduce (lambda x,y: x * y,lista)

print("lista =",lista,"\nProduto =",produto)

lista = [1,2,3,4,5,6]
lista1 = list(filter(lambda x:x % 2 != 0, lista))


print("lista =",lista,"\n\nlista1=",lista1)